### PR TITLE
Trim

### PR DESCRIPTION
**Pull request by IsaacCloos**
## Not found in this PR:
- disabling default trim
- updated unit tests

> These issues have been addressed in #98 

## Found in this PR:
- [X] code
- [X] documentation
- [X] example
- [X] readme
- [X] unit tests (for Trim)

Criticism encouraged! Happy to work at this until it's perfect.

### CODE REVIEW

**Comment by zhiburt** [comment]
That's good enough.
We can't do any better I think.

I would only add trim as function to format.
And maybe actually removed `Trim` itself or make it private.

```rust
impl Format {
  fn trim() -> Trim {
    Trim
  }
}
```

Plus I would do check if there's any top/bottom empty lines. And skip them.

**Comment by IsaacCloos** [comment]
> Plus I would do check if there's any top/bottom empty lines. And skip them.

You would like to retain new line escape characters? Current implementation removes all `White_Space` including `\n` and `\t`

**Comment by zhiburt** [comment]
> You would like to retain new line escape characters? Current implementation removes all White_Space including \n and \t

Yes removal of empty lines. which present before actual content and after.

**Comment by zhiburt** [comment]
It could be checked by something like this.

```rust
let trimmed_content = String::new();
let empty_lines_count = 0;
for line in content.lines() {
   let is_empty = line.trim().is_empty()
  if is_empty {
     empty_lines_count += 1;
     continue;
  }

     if empty_lines_count > 0 &&  trimmed_content.is_empty() {
         empty_lines_count = 0;
     }
      
     for _ in 0 .. empty_lines_count {
         trimmed_content.push('\n');
     }

      trimmed_content.push_str(line);
}
```

**Comment by IsaacCloos** [comment]
here is the string I'm testing this on:

`"[\n\t\"foo\",\n\t{\n\t\t\"bar\":1,\n\t\t\"baz\": [\n\t\t\t2,\n\t\t\t3\n\t\t]\n\t}\n]"`

taken from comment on ticket #61

**Comment by IsaacCloos** [comment]
PR #101 introduced new features to better dictate this setting to users

**Pull request closed without merging**
