### PR TITLE
Going through all the documentation and trying to use

### PR DESCRIPTION
**Pull request by CGMossa**
I really, really appreciate this package. And I wanted to go through it and
use the new way to refer to types in rustdoc. A few things have come up, that
would be nice if we could go through:

### CODE REVIEW

**Comment by CGMossa** [comment]
Also, I don't really understand the `ChangeRing`: https://github.com/CGMossa/tabled/blob/d40f8307ab00f85ea5d02b4a2ff6708421d9c99f/src/lib.rs#L204-L205

**Comment by zhiburt** [comment]
> Also, I don't really understand the ChangeRing: https://github.com/CGMossa/tabled/blob/d40f8307ab00f85ea5d02b4a2ff6708421d9c99f/src/lib.rs#L204-L205

`ChangeRing` is an old setting which was removed in regard of `Format` setting.
https://github.com/zhiburt/tabled/commit/6573015fb8777550d85800f3ba1c7f2645c07e9a#diff-a373be809d5fed898f6aa3a559af2601b9bd1c81ecb2a77be2821c77976a1312L47

So yes it certainly a bit outdated doc comment. Good catch :+1:

**Comment by zhiburt** [comment]
Overall I agree that documentation itself  deserve to be polished.

**Comment by zhiburt** [comment]
> For instance this line here: https://github.com/CGMossa/tabled/blob/25c331008023fecce39736ef4e3ec2d0adbe6631/src/panel.rs#L5-L6

You can basically remove any row/column by `Disable` option (Look and ./README.md).
And I was thinking that Remove something after adding a row may cause issues but actually now I am thinking about it and it must be fine. I mean the comment should be deleted..

**Comment by CGMossa** [comment]
Great! Thanks for the answer. I've removed these lines. Feel free to add any other suggestions, and merge it when you're happy with it.

**Review by zhiburt — CHANGES_REQUESTED** [review]
I actually like all your changes :100: 

And I wasn't be aware that when something is in scope you can refer on it in doc just like `[something]` so thanks for the lesson :)

But this feature brings compiler warnings. Wouldn't it be better to follow old fashioned (not actually) approach like this `[Table]: ./struct.Table.html`?

```bash
warning: unused import: `Table`
 --> src/alignment.rs:1:25
  |
1 | use crate::{CellOption, Table};
  |                         ^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `Table`
 --> src/disable.rs:1:30
  |
1 | use crate::{bounds_to_usize, Table, TableOption};
  |                              ^^^^^

warning: unused import: `papergrid::Grid`
 --> src/object.rs:6:5
  |
6 | use papergrid::Grid;
  |     ^^^^^^^^^^^^^^^

warning: unused import: `Disable`
 --> src/panel.rs:1:13
  |
1 | use crate::{Disable, TableOption};
  |             ^^^^^^^

warning: 4 warnings emitted
```

**Comment by CGMossa** [comment]
Based on what I've read here: https://github.com/rust-lang/rust/issues/79542, I think we should just do with the `#[allow(unused)]`. 
I'm pushing a commit that does this now.

**Comment by CGMossa** [comment]
The same issue showcases a "better" pattern that is also discouraged in the same thread:

```rust
/// [`HashMap`]
///
/// [`HashMap`]: std::collections::HashMap
pub fn foo() {}
```

**Comment by zhiburt** [comment]
Thanks for your PR.
And more importantly for your attention to the DOC. I'll try to work on it in a few days.

**Pull request merged**
