### PR TITLE
use inline format args (clippy::uninlined_format_args)

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by zhiburt** [comment]
Hi @danieleades 

Sorry for such a DELAY ....
I am actually not sure why I didn't answered earlier....

So I actually quite against this change as it will require some recent compiler version, which I tend to believe not good?
As far as I understand it won't compile on some versions right?

What do you think?

PS: Yes it's tests so maybe it doesn't matter a lot.

**Comment by zhiburt** [comment]
Welllllll

It seems to be a default now....

https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args

**Comment by danieleades** [comment]
> Welllllll
> 
> It seems to be a default now....
> 
> https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args

yes and no. Whether this lint gets applied or not depends on the configured MSRV. So it will depend on the decision in #264

**Review by zhiburt — APPROVED** [review]
Seems good;

Sorry for delay

**Pull request merged**
