### PR TITLE
fix(pagegrid): string_width

### PR DESCRIPTION
**Pull request by henrylee2cn**
```rust
let mut grid = Grid::new(1, 2);
grid.set(Entity::Cell(0, 0), Settings::new().text("哈哈"));
grid.set(Entity::Cell(0, 1), Settings::new().text("c"));
println!("{}", grid.to_string()); // fix panic
```

### CODE REVIEW

**Comment by zhiburt** [comment]
Hey @henrylee2cn it looks cool.

I'll get a more thorough look a bit later if you don't mind. 
 
PS: Don't worry about failed build as I messed Cargo.toml a little :smiley:

**Comment by zhiburt** [comment]
It's a good catch of panic. And you resolution mostly works except one thing. 
You solution doesn't address a multi line content.

https://github.com/zhiburt/tabled/blob/df81fa5c22d68f0727a1ba6cf9bdead279d3b702/papergrid/src/lib.rs#L904

I did fix it I hope

**Comment by zhiburt** [comment]
@henrylee2cn Please give me some response that you OK with my changes.

And could you enlighten me about hieroglyphs? 
Is this is correct behavior?

https://github.com/zhiburt/tabled/blob/5bf5394a60f695442646f8ab6c0b1dc20cb9889d/papergrid/src/lib.rs#L893-L922

**Comment by henrylee2cn** [comment]
ok, i am in adjustment

**Comment by henrylee2cn** [comment]
Your changes are ok

**Comment by zhiburt** [comment]
@henrylee2cn Thank you one more time for your contribution.

**Pull request merged**
