### PR TITLE
Example description revisions

### PR DESCRIPTION
**Pull request by IsaacCloos**
# Addressing #296

I've updated a handful of the examples, and would love some feedback before I proceed with the rest. I'm _attempting_ to keep the descriptions brief while identifying all the major ideas of each example and providing links where appropriate to further contextualize libraries referenced.

# Progress

- [X] csv_to_table
- [X] json_to_table
- [x] papergrid
- [x] static_table
- [x] table_to_html
- [x] tabled
    - [X] derive
- [X] tabled_derive

# Omitted [^1]

 - use_in_docs `static_table`
 - show `tabled`
 - terminal_size `tabled`

# Criticism Welcome 😄 
If you have any preferences whatsoever, please let me know and I will change what we've got so far. Or if you'd rather leave the examples as-is that's good too 👍🏻 

[^1]: tests not `cargo run --example` accessible

### CODE REVIEW

**Comment by zhiburt** [comment]
It feels like in some cases your description is more expressive then we have, as docs.

> ```rust
> //! * The [`IterTable::sniff()`] formatting function is used to control how many
> //! rows will be considered in determining column widths. Since the default sniff value is 1000,
> //! this is helpful for controlling large dataset display outputs.
> ```

vs 

```rust
/// Limit an amount of rows will be read for dimension estimations.
```

I do think we can go with what you'll chose the right one.

**Comment by IsaacCloos** [comment]
Ok, Thanks for the feedback! I'll work through the rest of these shortly 😄

**Comment by IsaacCloos** [comment]
I hope the goal of making the example browsing experience more educational for users was achieved.

# Criticism Welcome ❗ 
Please let me know if you'd like to see any changes 😄 
... or even rejecting the work I understand too. This is quite a lot to push through in one go, I may have gotten carried away writing these up ha!

**Comment by zhiburt** [comment]
Seems good to me.
As I said previously some comments have more information than the code docs.

I'll merge, thanks for such a heavy lifting.

___________________________________

What do you think about this section.
I was thinking previously it might be useful for someone who is not used to rust yet so they know how to run it.
But maybe it's just redundant?

```
//! This example can be run with the following command:
//!
//! `cargo run --example static_table`
```

**Comment by IsaacCloos** [comment]
> What do you think about this section. I was thinking previously it might be useful for someone who is not used to rust yet so they know how to run it. But maybe it's just redundant?
> 
> ```
> //! This example can be run with the following command:
> //!
> //! `cargo run --example static_table`
> ```

I agree. I've checked around a few other Rust projects, and haven't found another that specifies the command. 

However, there are a few examples that ask the user to write custom inputs outside of cargo, so perhaps keeping those would be helpful. e.g.
https://github.com/zhiburt/tabled/blob/5b254f3808bdc14cf97ffaea301b3e2e845b207a/tabled/examples/shadow.rs#L1-L3

or honestly these examples could be simplified? I don't see how using the Stdin adds to Shadow setting example, but I didn't think these doc revisions was the right place to challenge it.

This one I think is worth keeping for sure, since using Stdin is the whole point of the example.
https://github.com/zhiburt/tabled/blob/5b254f3808bdc14cf97ffaea301b3e2e845b207a/json_to_table/examples/reader.rs#L1-L3

**Pull request merged**
